package xjh.loveHome.IC.mode;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cust", "id", Cust.class);
		arp.addMapping("guard_device", "id", GuardDevice.class);
		arp.addMapping("plot_device", "id", PlotDevice.class);
		arp.addMapping("prop_plot", "id", PropPlot.class);
		arp.addMapping("sys_code", "id", SysCode.class);
		arp.addMapping("sys_exception_log", "id", SysExceptionLog.class);
		arp.addMapping("sys_pact", "id", SysPact.class);
		arp.addMapping("sys_res", "id", SysRes.class);
		arp.addMapping("xjh_advertising", "id", XjhAdvertising.class);
		arp.addMapping("xjh_footprint", "id", XjhFootprint.class);
	}
}

