package xjh.loveHome.IC.mode;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("guard_device", "id", GuardDevice.class);
		arp.addMapping("ic_card", "id", IcCard.class);
		arp.addMapping("plot_device", "id", PlotDevice.class);
		arp.addMapping("plot_user", "id", PlotUser.class);
		arp.addMapping("prop_plot", "id", PropPlot.class);
	}
}

