package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseCust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cust extends BaseCust<Cust> {
	public static final Cust dao = new Cust().dao();
}
