package xjh.loveHome.IC.mode;

import java.util.List;

import xjh.loveHome.IC.guard.cache.DeviceModeCache;
import xjh.loveHome.IC.mode.base.BaseGuardDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GuardDevice extends BaseGuardDevice<GuardDevice> {
	public static final GuardDevice dao = new GuardDevice().dao();
	/***
	 * 根据设备编号查询设备是否已注册
	 * ***/
	public boolean isSignined(String no) {
		if (getDeviceByNo(no)!=null) {
			return true;
		}
		return false;
	}
	
	
	public Integer getState(String no) throws Exception {
		if (getDeviceByNo(no)==null) {
			throw new Exception("this GuardDevice is null");
		}
		return null;
	}
	/***
	 * 用设备编号获取设备mode
	 * **/
	public GuardDevice getDeviceByNo(String no) {
		String sql="select * from guard_device where no=?";
		return findFirst(sql, no);
	}
	
	
	/***
	 * 获取所有设备mode
	 * **/
	public List<GuardDevice> getDeviceALL() {
		String sql="select * from guard_device";
		return find(sql);
	}
	
	
	/***
	 * 重写update与save方法，将写数据同步到cache中
	 * ***/
	@Override
	public boolean update() {
		if (super.update()) {
			DeviceModeCache.CACHE.addDeviceMode(this);
			return true;
		}
		return false;
	}
	
	/***
	 * 重写update与save方法，将写数据同步到cache中
	 * ***/
	@Override
	public boolean save() {
		if (super.save()) {
			DeviceModeCache.CACHE.addDeviceMode(this);
			return true;
		}
		return false;
	}
	
	
}
