package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseIcCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IcCard extends BaseIcCard<IcCard> {
	public static final IcCard dao = new IcCard().dao();
}
