package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BasePlotUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlotUser extends BasePlotUser<PlotUser> {
	public static final PlotUser dao = new PlotUser().dao();
}
