package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BasePlotDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlotDevice extends BasePlotDevice<PlotDevice> {
	public static final PlotDevice dao = new PlotDevice().dao();
}
