package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BasePropPlot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropPlot extends BasePropPlot<PropPlot> {
	public static final PropPlot dao = new PropPlot().dao();
}
