package xjh.loveHome.IC.mode;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.jfinal.plugin.activerecord.Page;

import xjh.loveHome.IC.mode.base.BasePropPlot;
import xjh.loveHome.IC.uitils.StringUitils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropPlot extends BasePropPlot<PropPlot> {
	public static final PropPlot dao = new PropPlot().dao();

	public Page<PropPlot> queryProps(Integer pageNo, Integer pageRow, Map<String, String> queryparam) {
		List<Object> params=new ArrayList<>();
		StringBuilder selectsql=new StringBuilder();
		selectsql.append("select *");
		StringBuilder formsql=new StringBuilder();
		formsql.append(" from prop_plot plot");
		formsql.append(" where 1=1");
		if (StringUitils.isNotBlank(queryparam.get("city"))) {
			formsql.append(" and plot.region=?");
			params.add(queryparam.get("city"));
		}
		if (StringUitils.isNotBlank(queryparam.get("name"))) {
			formsql.append(" and plot.name=?");
			params.add(queryparam.get("name"));
		}
		return dao.paginate(pageNo, pageRow,selectsql.toString(),formsql.toString(),params.toArray());
	}
}
