package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseSysCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysCode extends BaseSysCode<SysCode> {
	public static final SysCode dao = new SysCode().dao();
}
