package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseSysExceptionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysExceptionLog extends BaseSysExceptionLog<SysExceptionLog> {
	public static final SysExceptionLog dao = new SysExceptionLog().dao();
}
