package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseSysPact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPact extends BaseSysPact<SysPact> {
	public static final SysPact dao = new SysPact().dao();
}
