package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseSysRes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRes extends BaseSysRes<SysRes> {
	public static final SysRes dao = new SysRes().dao();
}
