package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseXjhAdvertising;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XjhAdvertising extends BaseXjhAdvertising<XjhAdvertising> {
	public static final XjhAdvertising dao = new XjhAdvertising().dao();
}
