package xjh.loveHome.IC.mode;

import xjh.loveHome.IC.mode.base.BaseXjhFootprint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XjhFootprint extends BaseXjhFootprint<XjhFootprint> {
	public static final XjhFootprint dao = new XjhFootprint().dao();
}
