package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlotUser<M extends BasePlotUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPlotId(java.lang.Long plotId) {
		set("plot_id", plotId);
	}
	
	public java.lang.Long getPlotId() {
		return getLong("plot_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setIcNo(java.lang.String icNo) {
		set("ic_no", icNo);
	}
	
	public java.lang.String getIcNo() {
		return getStr("ic_no");
	}

}
