package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePropPlot<M extends BasePropPlot<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCompleteDate(java.util.Date completeDate) {
		set("complete_date", completeDate);
	}
	
	public java.util.Date getCompleteDate() {
		return get("complete_date");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}
	
	public java.lang.Integer getProvinceId() {
		return getInt("province_id");
	}

	public void setRegionId(java.lang.Integer regionId) {
		set("region_id", regionId);
	}
	
	public java.lang.Integer getRegionId() {
		return getInt("region_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}
	
	public java.lang.Integer getCountyId() {
		return getInt("county_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setImgPath(java.lang.String imgPath) {
		set("img_path", imgPath);
	}
	
	public java.lang.String getImgPath() {
		return getStr("img_path");
	}

	public void setAlias(java.lang.String alias) {
		set("alias", alias);
	}
	
	public java.lang.String getAlias() {
		return getStr("alias");
	}

	public void setLongitude(java.math.BigDecimal Longitude) {
		set("Longitude", Longitude);
	}
	
	public java.math.BigDecimal getLongitude() {
		return get("Longitude");
	}

	public void setLatitude(java.math.BigDecimal Latitude) {
		set("Latitude", Latitude);
	}
	
	public java.math.BigDecimal getLatitude() {
		return get("Latitude");
	}

}
