package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXjhFootprint<M extends BaseXjhFootprint<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAdId(java.lang.Long adId) {
		set("ad_id", adId);
	}
	
	public java.lang.Long getAdId() {
		return getLong("ad_id");
	}

	public void setPuId(java.lang.Long puId) {
		set("pu_id", puId);
	}
	
	public java.lang.Long getPuId() {
		return getLong("pu_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setParId(java.lang.Long parId) {
		set("par_id", parId);
	}
	
	public java.lang.Long getParId() {
		return getLong("par_id");
	}

	public void setMoment(java.util.Date moment) {
		set("moment", moment);
	}
	
	public java.util.Date getMoment() {
		return get("moment");
	}

	public void setEarnCash(java.math.BigDecimal earnCash) {
		set("earn_cash", earnCash);
	}
	
	public java.math.BigDecimal getEarnCash() {
		return get("earn_cash");
	}

	public void setEarnPoi(java.lang.Long earnPoi) {
		set("earn_poi", earnPoi);
	}
	
	public java.lang.Long getEarnPoi() {
		return getLong("earn_poi");
	}

	public void setTerminalType(java.lang.String terminalType) {
		set("terminal_type", terminalType);
	}
	
	public java.lang.String getTerminalType() {
		return getStr("terminal_type");
	}

	public void setAdSeq(java.lang.Long adSeq) {
		set("ad_seq", adSeq);
	}
	
	public java.lang.Long getAdSeq() {
		return getLong("ad_seq");
	}

	public void setAdTitle(java.lang.String adTitle) {
		set("ad_title", adTitle);
	}
	
	public java.lang.String getAdTitle() {
		return getStr("ad_title");
	}

}
