package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIcCard<M extends BaseIcCard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	public java.lang.String getNo() {
		return getStr("no");
	}

	public void setMasterName(java.lang.String masterName) {
		set("master_name", masterName);
	}
	
	public java.lang.String getMasterName() {
		return getStr("master_name");
	}

}
