package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlotDevice<M extends BasePlotDevice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPlotId(java.lang.Long plotId) {
		set("plot_id", plotId);
	}
	
	public java.lang.Long getPlotId() {
		return getLong("plot_id");
	}

	public void setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
	}
	
	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	public void setScope(java.lang.Boolean scope) {
		set("scope", scope);
	}
	
	public java.lang.Boolean getScope() {
		return get("scope");
	}

}
