package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXjhAdvertising<M extends BaseXjhAdvertising<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPubId(java.lang.Long pubId) {
		set("pubId", pubId);
	}
	
	public java.lang.Long getPubId() {
		return getLong("pubId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setTitleImage(java.lang.String titleImage) {
		set("titleImage", titleImage);
	}
	
	public java.lang.String getTitleImage() {
		return getStr("titleImage");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setMedia(java.lang.String media) {
		set("media", media);
	}
	
	public java.lang.String getMedia() {
		return getStr("media");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setOnceBrowseSendType(java.lang.Integer onceBrowseSendType) {
		set("onceBrowseSendType", onceBrowseSendType);
	}
	
	public java.lang.Integer getOnceBrowseSendType() {
		return getInt("onceBrowseSendType");
	}

	public void setOnceBrowseSendCash(java.math.BigDecimal onceBrowseSendCash) {
		set("onceBrowseSendCash", onceBrowseSendCash);
	}
	
	public java.math.BigDecimal getOnceBrowseSendCash() {
		return get("onceBrowseSendCash");
	}

	public void setOnceBrowseSendIntegral(java.lang.Long onceBrowseSendIntegral) {
		set("onceBrowseSendIntegral", onceBrowseSendIntegral);
	}
	
	public java.lang.Long getOnceBrowseSendIntegral() {
		return getLong("onceBrowseSendIntegral");
	}

	public void setPredictBrowseNum(java.lang.Long predictBrowseNum) {
		set("predictBrowseNum", predictBrowseNum);
	}
	
	public java.lang.Long getPredictBrowseNum() {
		return getLong("predictBrowseNum");
	}

	public void setShareSendType(java.lang.Integer shareSendType) {
		set("shareSendType", shareSendType);
	}
	
	public java.lang.Integer getShareSendType() {
		return getInt("shareSendType");
	}

	public void setOnceShareSendIntegral(java.lang.Long onceShareSendIntegral) {
		set("onceShareSendIntegral", onceShareSendIntegral);
	}
	
	public java.lang.Long getOnceShareSendIntegral() {
		return getLong("onceShareSendIntegral");
	}

	public void setOnceShareSendCash(java.math.BigDecimal onceShareSendCash) {
		set("onceShareSendCash", onceShareSendCash);
	}
	
	public java.math.BigDecimal getOnceShareSendCash() {
		return get("onceShareSendCash");
	}

	public void setPredictShareNum(java.lang.Long predictShareNum) {
		set("predictShareNum", predictShareNum);
	}
	
	public java.lang.Long getPredictShareNum() {
		return getLong("predictShareNum");
	}

	public void setResidueLimit(java.lang.Integer residueLimit) {
		set("residueLimit", residueLimit);
	}
	
	public java.lang.Integer getResidueLimit() {
		return getInt("residueLimit");
	}

	public void setTotalIntegral(java.lang.Long totalIntegral) {
		set("totalIntegral", totalIntegral);
	}
	
	public java.lang.Long getTotalIntegral() {
		return getLong("totalIntegral");
	}

	public void setTotalCash(java.math.BigDecimal totalCash) {
		set("totalCash", totalCash);
	}
	
	public java.math.BigDecimal getTotalCash() {
		return get("totalCash");
	}

	public void setCreationTime(java.util.Date creationTime) {
		set("creationTime", creationTime);
	}
	
	public java.util.Date getCreationTime() {
		return get("creationTime");
	}

	public void setAdStatus(java.lang.String adStatus) {
		set("adStatus", adStatus);
	}
	
	public java.lang.String getAdStatus() {
		return getStr("adStatus");
	}

	public void setAuditPassTime(java.util.Date auditPassTime) {
		set("auditPassTime", auditPassTime);
	}
	
	public java.util.Date getAuditPassTime() {
		return get("auditPassTime");
	}

	public void setIsToAnswer(java.lang.String isToAnswer) {
		set("isToAnswer", isToAnswer);
	}
	
	public java.lang.String getIsToAnswer() {
		return getStr("isToAnswer");
	}

	public void setShowArea(java.lang.String showArea) {
		set("showArea", showArea);
	}
	
	public java.lang.String getShowArea() {
		return getStr("showArea");
	}

	public void setCountdown(java.lang.Integer countdown) {
		set("countdown", countdown);
	}
	
	public java.lang.Integer getCountdown() {
		return getInt("countdown");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

}
