package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGuardDevice<M extends BaseGuardDevice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	public java.lang.String getNo() {
		return getStr("no");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setProt(java.lang.Integer prot) {
		set("prot", prot);
	}
	
	public java.lang.Integer getProt() {
		return getInt("prot");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setPart(java.lang.Long part) {
		set("part", part);
	}
	
	public java.lang.Long getPart() {
		return getLong("part");
	}

	public void setCommunication(java.lang.Integer communication) {
		set("communication", communication);
	}
	
	public java.lang.Integer getCommunication() {
		return getInt("communication");
	}

}
