package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCust<M extends BaseCust<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCustType(java.lang.String custType) {
		set("cust_type", custType);
	}
	
	public java.lang.String getCustType() {
		return getStr("cust_type");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setCustName(java.lang.String custName) {
		set("cust_name", custName);
	}
	
	public java.lang.String getCustName() {
		return getStr("cust_name");
	}

	public void setBirthDate(java.util.Date birthDate) {
		set("birth_date", birthDate);
	}
	
	public java.util.Date getBirthDate() {
		return get("birth_date");
	}

	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}
	
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setPayPassword(java.lang.String payPassword) {
		set("pay_password", payPassword);
	}
	
	public java.lang.String getPayPassword() {
		return getStr("pay_password");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	public java.lang.String getNote() {
		return getStr("note");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channel_id", channelId);
	}
	
	public java.lang.String getChannelId() {
		return getStr("channel_id");
	}

	public void setLoginAmount(java.lang.Integer loginAmount) {
		set("login_amount", loginAmount);
	}
	
	public java.lang.Integer getLoginAmount() {
		return getInt("login_amount");
	}

	public void setBoughtAmount(java.math.BigDecimal boughtAmount) {
		set("bought_amount", boughtAmount);
	}
	
	public java.math.BigDecimal getBoughtAmount() {
		return get("bought_amount");
	}

	public void setBoughtNumber(java.lang.Integer boughtNumber) {
		set("bought_number", boughtNumber);
	}
	
	public java.lang.Integer getBoughtNumber() {
		return getInt("bought_number");
	}

	public void setCommentNumber(java.lang.Integer commentNumber) {
		set("comment_number", commentNumber);
	}
	
	public java.lang.Integer getCommentNumber() {
		return getInt("comment_number");
	}

	public void setContinuousDay(java.lang.Integer continuousDay) {
		set("continuous_day", continuousDay);
	}
	
	public java.lang.Integer getContinuousDay() {
		return getInt("continuous_day");
	}

	public void setPointTime(java.lang.Integer pointTime) {
		set("point_time", pointTime);
	}
	
	public java.lang.Integer getPointTime() {
		return getInt("point_time");
	}

	public void setCumulPoint(java.math.BigDecimal cumulPoint) {
		set("cumul_point", cumulPoint);
	}
	
	public java.math.BigDecimal getCumulPoint() {
		return get("cumul_point");
	}

	public void setShopPoint(java.lang.Integer shopPoint) {
		set("shop_point", shopPoint);
	}
	
	public java.lang.Integer getShopPoint() {
		return getInt("shop_point");
	}

	public void setSignDays(java.lang.Integer signDays) {
		set("sign_days", signDays);
	}
	
	public java.lang.Integer getSignDays() {
		return getInt("sign_days");
	}

	public void setLastSignTime(java.util.Date lastSignTime) {
		set("last_sign_time", lastSignTime);
	}
	
	public java.util.Date getLastSignTime() {
		return get("last_sign_time");
	}

	public void setSignPointTime(java.lang.Integer signPointTime) {
		set("sign_point_time", signPointTime);
	}
	
	public java.lang.Integer getSignPointTime() {
		return getInt("sign_point_time");
	}

	public void setSumGoldCoins(java.lang.Integer sumGoldCoins) {
		set("sum_gold_coins", sumGoldCoins);
	}
	
	public java.lang.Integer getSumGoldCoins() {
		return getInt("sum_gold_coins");
	}

	public void setFacePath(java.lang.String facePath) {
		set("face_path", facePath);
	}
	
	public java.lang.String getFacePath() {
		return getStr("face_path");
	}

	public void setPushUserAccount(java.lang.String pushUserAccount) {
		set("push_user_account", pushUserAccount);
	}
	
	public java.lang.String getPushUserAccount() {
		return getStr("push_user_account");
	}

	public void setWeixinHeadimgurl(java.lang.String weixinHeadimgurl) {
		set("weixin_headimgurl", weixinHeadimgurl);
	}
	
	public java.lang.String getWeixinHeadimgurl() {
		return getStr("weixin_headimgurl");
	}

	public void setIsNotice(java.lang.Integer isNotice) {
		set("is_notice", isNotice);
	}
	
	public java.lang.Integer getIsNotice() {
		return getInt("is_notice");
	}

	public void setBalVal(java.math.BigDecimal balVal) {
		set("bal_val", balVal);
	}
	
	public java.math.BigDecimal getBalVal() {
		return get("bal_val");
	}

	public void setRelationId(java.lang.Integer relationId) {
		set("relation_id", relationId);
	}
	
	public java.lang.Integer getRelationId() {
		return getInt("relation_id");
	}

	public void setWeixinNo(java.lang.String weixinNo) {
		set("weixin_no", weixinNo);
	}
	
	public java.lang.String getWeixinNo() {
		return getStr("weixin_no");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setSyCustId(java.lang.String syCustId) {
		set("sy_cust_id", syCustId);
	}
	
	public java.lang.String getSyCustId() {
		return getStr("sy_cust_id");
	}

	public void setSubscribe(java.lang.String subscribe) {
		set("subscribe", subscribe);
	}
	
	public java.lang.String getSubscribe() {
		return getStr("subscribe");
	}

}
