package xjh.loveHome.IC.mode.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePropPlot<M extends BasePropPlot<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}
	
	public java.lang.String getRegion() {
		return getStr("region");
	}

	public void setCounty(java.lang.String county) {
		set("county", county);
	}
	
	public java.lang.String getCounty() {
		return getStr("county");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}
	
	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public void setImgSource(java.lang.String imgSource) {
		set("img_source", imgSource);
	}
	
	public java.lang.String getImgSource() {
		return getStr("img_source");
	}

	public void setLongitude(java.math.BigDecimal Longitude) {
		set("Longitude", Longitude);
	}
	
	public java.math.BigDecimal getLongitude() {
		return get("Longitude");
	}

	public void setLatitude(java.math.BigDecimal Latitude) {
		set("Latitude", Latitude);
	}
	
	public java.math.BigDecimal getLatitude() {
		return get("Latitude");
	}

}
